# SPDX-License-Identifier: Apache-2.0
# # Copyright Contributors to the ODPi Egeria project.
#
name: Egeria react UI build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Run client/server in parallel. 
# Code checkout is small so low overhead, 
# npm build is slow, so benefits from parallelism
jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies for client
        working-directory: ./cra-client
        run: npm install
      - name: Build client
        working-directory: ./cra-client
        run: npm run build
        env:
          CI: false
          NODE_OPTIONS: "--max_old_space_size=6144"
      - name: Install dependencies for server
        working-directory: ./cra-server
        run: npm install
      - name: Build server
        working-directory: ./cra-server
        run: npm run build
        env:
          CI: false
          NODE_OPTIONS: "--max_old_space_size=6144"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        if: ${{ github.event_name == 'push' && github.repository == 'odpi/egeria-react-ui' }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push:  ${{ github.event_name == 'push' && github.repository == 'odpi/egeria-react-ui' }} 
          tags: odpi/egeria-presentation-server:latest
          context: .
          file: ./Dockerfile
          #build-args: |
          #  arg1=value1
          #  arg2=value2
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
